apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./components/reddog.binding.receipt.yaml
- ./components/reddog.binding.virtualworker.yaml
- ./components/reddog.config.yaml
- ./components/reddog.pubsub.yaml
- ./components/reddog.secretstore.yaml
- ./components/reddog.state.loyalty.yaml
- ./components/reddog.state.makeline.yaml
- ./deployments/accounting-service.yaml
- ./deployments/bootstrapper.yaml
- ./deployments/loyalty-service.yaml
- ./deployments/make-line-service.yaml
- ./deployments/order-service.yaml
- ./deployments/receipt-generation-service.yaml
- ./deployments/ui.yaml
- ./deployments/virtual-customers.yaml
- ./deployments/virtual-worker.yaml
