apiVersion: apps/v1
kind: Deployment
metadata:
  name: corp-transfer-service
  namespace: reddog-retail
  labels:
    app: corp-transfer-service
spec:
  selector:
    matchLabels:
      app: corp-transfer-service
  template:
    metadata:
      labels:
        app: corp-transfer-service
    spec:
      containers:
      - name: corp-transfer-service
        image: ghcr.io/cloudnativegbb/paas-vnext/corp-transfer-service:0.3
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: RabbitOrderCompletedFx
        - name: AzureFunctionsJobHost__functions__1
          value: RabbitOrdersFx
        envFrom:
        - secretRef:
            name: corp-transfer-service
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: corp-transfer-service
  namespace: reddog-branch    
  labels: {}
spec:
  scaleTargetRef:
    name: corp-transfer-service
  pollingInterval: 20
  cooldownPeriod: 300
  triggers:
  - type: rabbitmq
    metadata:
      direction: in
      queueName: corp-transfer-ordercompleted
      hostFromEnv: rabbitMQConnectionAppSetting
  - type: rabbitmq
    metadata:
      direction: in
      queueName: corp-transfer-orders
      hostFromEnv: rabbitMQConnectionAppSetting