apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: reddog-branch
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "ui"
        dapr.io/config: "reddog.config"
    spec:
      containers:
        - name: ui
          image: "ghcr.io/cloudnativegbb/paas-vnext/reddog-ui:latest"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
          - name: VUE_APP_IS_CORP
            value: "false"          
          - name: VUE_APP_STORE_ID
            valueFrom:
              secretKeyRef:
                  name: branch.config
                  key: store_id
          - name: VUE_APP_MAKELINE_BASE_URL
            valueFrom:
              secretKeyRef:
                  name: branch.config
                  key: makeline_base_url
          - name: VUE_APP_ACCOUNTING_BASE_URL
            valueFrom:
              secretKeyRef:
                  name: branch.config
                  key: accounting_base_url