apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-worker
  namespace: reddog-retail
spec:
  template:
    spec:
      containers:
      - name: virtual-worker
        env:
        - name: STORE_ID
          value: Redmond
